# Generated by Django 5.0.3 on 2024-06-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
