# Generated by Django 5.0.3 on 2024-05-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_package_category_package_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ManyToManyField(related_name='packages', to='department.category'),
        ),
    ]
