# Generated by Django 5.0.3 on 2024-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_package_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='functions',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
