# Generated by Django 5.0.3 on 2024-05-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_package_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_name',
        ),
    ]
