# Generated by Django 5.0.3 on 2024-06-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_packageorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='department.package'),
        ),
    ]
