# Generated by Django 5.0.3 on 2024-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_alter_portfolio_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Team_member/')),
            ],
        ),
    ]
