# Generated by Django 5.0.3 on 2024-08-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Client/')),
            ],
        ),
    ]
